### ISSUE TITLE
Brush doesn't apply to all devices

### ISSUE THREAD

**Issue by Debugga-nb** [Artemis-RGB/Artemis.Plugins.Wrappers#1]
This may not be an "issue"; so much as a limitation.

I have a Razer mouse, and keypad; and a corsair strafe keyboard. 
I was kinda hoping this brush would be able to "extend" chroma features from games into my keyboard as well. 

I see the razers lighting up with chroma effects, but the keyboard is still cycling the "background" layer.

Feel free to delete this issue, if it's nothing that can be tweaked/fixed.

**Comment by RobertBeekman** [comment]
Hi, this is something that should just work. Can you make sure the layer is on top? You can drag them in the top-right panel, the order matters.

If you are still having trouble please share a screenshot of your profile

**Comment by Debugga-nb** [comment]
I copied the default "noise" profile, and made the background transparent (I'm using this profile as a tester)
![image](https://user-images.githubusercontent.com/54511646/155216620-36145490-420d-4f67-9a28-566b2b1eb0dd.png)
![image](https://user-images.githubusercontent.com/54511646/155217430-ffb5ad21-7d07-4746-ab4b-3ba993863bfb.png)

Just for awareness, I'm using Halo Infinite to test (it's just one I know is installed and triggers the Razer Chroma stuff)
Right now, with the game in the background. I can tell that the type layer is not visible, as the Razer layer took over.

I started diving into Artemis to basically do just this lol, I wanted to get my Corsair keyboard to talk friendly with the Razer Chroma auto-game color feature.

Edit: OH! I bet it's synapse/icue taking over, and not the plugin.

**Comment by RobertBeekman** [comment]
To me it looks like you set it up correctly, do you have Overwatch or another game to test with?

**Comment by Debugga-nb** [comment]
It looks like Synapse is running it's chroma app for overwatch, so it wasn't artemis handling it at all. I tried disabling it, but artemis doesn't take over. 

I feel like I'm missing a piece

**Comment by Debugga-nb** [comment]
I've set iCUE to allow software, but not game integration. 
And Synapse trys to run chroma apps for games, instead of forcing everything through the Artemis app (which is enabled) 

So, I'm missing the step where razer hands the game chroma info to the plugin, to artemis, to replicate it over to the keyboard?

I'm not sure where it's pulling the Halo infinite one, it doesn't have an app to toggle, but overwatch does.

**Comment by diogotr7** [comment]
The razer wrapper isn't very good yet. Besides, most games (especially newer competitive ones, like halo infinite) will block the dll anyway. I recommend using my Chroma plugin instead. It does require the Razer SDK to be installed, though.

**Comment by diogotr7** [comment]
Also, razer never "hands" artemis the data, we have to grab it from the sdk ourselves.

**Comment by Debugga-nb** [comment]
> 
I just grabbed and tried that out, with no issue. So I let Synapse do it's thing, and enable the chroma game applet (and handle light for the razer stuff? looks like), and Artemis is grabbing it for my keyboard. 

The Chroma plugin seems to be doing what I was looking for. Thank you Diogtr7 and RobertBeekman

**Comment by ecto1a2003** [comment]
> Razer SDK

is the sdk built into synapse or seperate dl?
