### ISSUE TITLE
Uable to recognise games with razer wrapper

### ISSUE THREAD

**Issue by 294762577** [Artemis-RGB/Artemis.Plugins.Wrappers#2]
Hi There,
After installing the plugin and put razer wrapper layer to the top. I ran games(supported by razer chroma) but none of the games' name is written into Artemis log. And light effect is not working.

I'm using a razer mouse and hyperx keyboard. both handled via OpenRGB.

Any help would be appreciated.

**Comment by AndreCox** [comment]
I believe you have to have razer synapse installed.

**Comment by 294762577** [comment]
> 

Hi Andre, thanks for you reply. 

Razer synapse is installed cuz i'm using a Razer mouse.

I also tried reinstalling all Razer software but still no luck fixing the issue...

**Comment by AndreCox** [comment]
Yeah just tested it out I have a razer keyboard and am using OpenRGB managing everything I tried doom and it looked like the effects worked on the keyboard however it gave me this weird flickering effect as both OpenRGB and Synapse was trying to control it

Hopefully there will be a fix soon

**Comment by 294762577** [comment]
> Yeah just tested it out I have a razer keyboard and am using OpenRGB managing everything I tried doom and it looked like the effects worked on the keyboard however it gave me this weird flickering effect as both OpenRGB and Synapse was trying to control it
> 
> Hopefully there will be a fix soon

Haha, thanks for testing it out. At least you get some light coming up. 

I applied the razer layer to both my razer mouse and HyperX keyboard, but couldn't get any light in any of the supported game.

I guess we just have to wait for a fix if not much be done by ourselves :)

**Comment by diogotr7** [comment]
The wrapper is not the same as the Chroma plugin on my repository. This wrapper does not require synapse to be installed, but the custom dll is blocked by most recent games. For most cases you should use the Chroma plugin instead of this Razer wrapper one.

[Chroma Plugin](https://github.com/diogotr7/Artemis.Plugins)

**Comment by diogotr7** [comment]
If you have issues with the chroma plugin, submit them to that repository instead of this one.
